### ISSUE TITLE
aws-health-notifier

### ISSUE THREAD

**Issue by BaselAl** [trussworks/terraform-aws-health-notifications#8]
Hi Trussworks team,

I use terraform 14 and follow the steps described in the repo:
```
module "health-notifier" {
  source                = "trussworks/health-notifications/aws"
  version               = "3.1.0"
  environment           = "any"
  s3_bucket             = "lambda-health-notification"
  slack_channel         = "aws-events"
  ssm_slack_webhook_url = "https://hooks.slack.com/services...."
  version_to_deploy     = "3.0"
}

```

Before the above steps, I had already created s3 bucket(lambda-health-notification) with the following folders *truss-aws-tools/3.0/truss-aws-tools.zip**
The zip is dowloaded from: https://github.com/trussworks/truss-aws-tools/releases/v3.0 and uploaded to S3(lambda-health-notification). Did I do these steps correctly because they are not mentioned in your instruction?

Could you please tell me how to properly test the AWS Lambda function since I have events in the AWS event log but I don't get them in Slack?

**Comment by rpdelaney** [comment]
Hi @BaselAl ! We're sorry about the slow turn-around on this. I'm going to assume you got this sorted and close this as stale, but if you still need help, let me know and we can re-open discussion.
